var topoData = {
    "nodes": [{
        "id": "CMZJ::E2CVPN-000.01",
        "name": "E2CVPN",
        "desc": "Represents E2CVPN",
        "alarm": 0,
        "displayType": "cfs",
        "align": "left",
        "perf": 1
    }, {
        "id": "CMZJ::CPE-000.01",
        "name": "CPE",
        "desc": "Represents CPE",
        "alarm": 0,
        "displayType": "rfs",
        "align": "left",
        "perf": 1
    }, {
        "id": "CMZJ::SubNet30-000.00",
        "name": "SubNet30",
        "desc": "Represents a 30 subnet",
        "alarm": 0,
        "displayType": "rfs",
        "align": "left",
        "perf": 1
    }, {
        "id": "CMZJ::SubNet16-000.00",
        "name": "SubNet16",
        "desc": "Represents a 16 subnet",
        "alarm": 0,
        "displayType": "rfs",
        "align": "right",
        "perf": 1
    }, {
        "id": "CMZJ::SubNet24-000.00",
        "name": "SubNet24",
        "desc": "Represents a 24 subnet",
        "alarm": 0,
        "displayType": "rfs",
        "align": "right",
        "perf": 1
    }, {
        "id": "CMZJ::SubNet16-000.01",
        "name": "SubNet16",
        "desc": "Represents a 16 subnet",
        "alarm": 0,
        "displayType": "rfs",
        "align": "right",
        "perf": 1
    }, {
        "id": "CMZJ::IPAddrRange-000.00",
        "name": "IPAddrRange",
        "desc": "Represents a range of ipaddress",
        "alarm": 0,
        "displayType": "cfs",
        "align": "right",
        "perf": 1
    }, {
        "id": "CMZJ::RMS-000.00",
        "name": "RMS",
        "desc": "Represents RMS",
        "alarm": 0,
        "displayType": "rfs",
        "align": "right",
        "perf": 1
    }, {
        "id": "CMZJ::OSS-000.00",
        "name": "OSS",
        "desc": "Represents OSS",
        "alarm": 0,
        "displayType": "rfs",
        "align": "right",
        "perf": 1
    }, {
        "id": "CMZJ::CustomerAddrMgr-000.01",
        "name": "CustomerAddrMgr",
        "desc": "Represents the mgr of SubConnections",
        "alarm": 0,
        "displayType": "cfs",
        "align": "right",
        "perf": 1
    }, {
        "id": "CMZJ::WAN-000.00",
        "name": "WAN",
        "desc": "Represents WAN for Enterprises&Governments",
        "alarm": 0,
        "displayType": "undefined",
        "align": "right",
        "perf": 1
    }, {
        "id": "CMZJ::E2CVPN-000.00",
        "name": "E2CVPN",
        "desc": "Represents E2CVPN",
        "alarm": 0,
        "displayType": "rfs",
        "align": "right",
        "perf": 1
    }, {
        "id": "CMZJ::WanAccess-000.00",
        "name": "WanAccess",
        "desc": "Represents an access to WAN for CPE ",
        "alarm": 0,
        "displayType": "undefined",
        "align": "left",
        "perf": 1
    }, {
        "id": "CMZJ::LeasedLine-000.00",
        "name": "LeasedLine",
        "desc": "Represents LeasedLine",
        "alarm": 0,
        "displayType": "rfs",
        "align": "left",
        "perf": 1
    }, {
        "id": "CMZJ::EOMS-000.00",
        "name": "EOMS",
        "desc": "Represents EOMS",
        "alarm": 0,
        "displayType": "rfs",
        "align": "right",
        "perf": 1
    }, {
        "id": "CMZJ::VPCAccess-000.00",
        "name": "VPCAccess",
        "desc": "Represents Site to VPC access",
        "alarm": 0,
        "displayType": "rfs",
        "align": "left",
        "perf": 1
    }, {
        "id": "CMZJ::SiteAccess-000.00",
        "name": "SiteAccess",
        "desc": "Represents VPC access given site",
        "alarm": 0,
        "displayType": "rfs",
        "align": "left",
        "perf": 1
    }, {
        "id": "CMZJ::CloudPlatform-000.00",
        "name": "CloudPlatform",
        "desc": "Represents cloud platform for Enterprises&Governments",
        "alarm": 0,
        "displayType": "undefined",
        "align": "right",
        "perf": 1
    }, {
        "id": "CMZJ::Cloud-000.00",
        "name": "Cloud",
        "desc": "Represents Cloud for Enterprises&Governments",
        "alarm": 0,
        "displayType": "undefined",
        "align": "right",
        "perf": 1
    }, {
        "id": "CMZJ::W2C-000.00",
        "name": "W2C",
        "desc": "Wan to Cloud connection",
        "alarm": 0,
        "displayType": "undefined",
        "align": "left",
        "perf": 1
    }, {
        "id": "CMZJ::SubConnection-000.00",
        "name": "SubConnection",
        "desc": "Represents a 30 subnet with vlan",
        "alarm": 0,
        "displayType": "rfs",
        "align": "left",
        "perf": 1
    }, {
        "id": "CMZJ::SubNet24VLAN-000.00",
        "name": "SubNet24VLAN",
        "desc": "Represents a 24 subnet with VLAN range",
        "alarm": 0,
        "displayType": "rfs",
        "align": "right",
        "perf": 1
    }, {
        "id": "CMZJ::SubConnMgr-000.00",
        "name": "SubConnMgr",
        "desc": "Represents the mgr of SubConnections",
        "alarm": 0,
        "displayType": "cfs",
        "align": "right",
        "perf": 1
    }, {
        "id": "CMZJ::WanNode-000.00",
        "name": "WanNode",
        "desc": "Represents WanNode",
        "alarm": 0,
        "displayType": "rfs",
        "align": "left",
        "perf": 1
    }, {
        "id": "CMZJ::CloudAccess-000.00",
        "name": "CloudAccess",
        "desc": "Represents an access to cloud for customer ",
        "alarm": 0,
        "displayType": "undefined",
        "align": "left",
        "perf": 1
    }, {
        "id": "CMZJ::WanCE-000.00",
        "name": "WanCE",
        "desc": "WanCE",
        "alarm": 0,
        "displayType": "undefined",
        "align": "right",
        "perf": 1
    }, {
        "id": "CMZJ::CloudNode-000.00",
        "name": "CloudNode",
        "desc": "Represents CloudNode",
        "alarm": 0,
        "displayType": "rfs",
        "align": "left",
        "perf": 1
    }, {
        "id": "CMZJ::VPNAccess-000.00",
        "name": "VPNAccess",
        "desc": "Represents an access to VPN for VPC ",
        "alarm": 0,
        "displayType": "undefined",
        "align": "left",
        "perf": 1
    }, {
        "id": "CMZJ::CloudCE-000.00",
        "name": "CloudCE",
        "desc": "CloudCE",
        "alarm": 0,
        "displayType": "undefined",
        "align": "right",
        "perf": 1
    }, {
        "id": "CMZJ::RouteCfg-000.00",
        "name": "RouteCfg",
        "desc": "Represents Route config for VPN",
        "alarm": 0,
        "displayType": "undefined",
        "align": "left",
        "perf": 1
    }, {
        "id": "CMZJ::VPCRoute-000.00",
        "name": "VPCRoute",
        "desc": "Represents Route config for VPC",
        "alarm": 0,
        "displayType": "undefined",
        "align": "left",
        "perf": 1
    }, {
        "id": "CMZJ::Customer-000.00",
        "name": "Customer",
        "desc": "Represents Customer",
        "alarm": 0,
        "displayType": "account",
        "align": "right",
        "perf": 1
    }],
    "links": [{
        "source": "CMZJ::E2CVPN-000.01",
        "target": "CMZJ::CPE-000.01",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::SubNet16-000.00",
        "target": "CMZJ::SubNet30-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::SubNet24-000.00",
        "target": "CMZJ::SubNet30-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::SubNet16-000.01",
        "target": "CMZJ::SubNet30-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::IPAddrRange-000.00",
        "target": "CMZJ::SubNet16-000.01",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::RMS-000.00",
        "target": "CMZJ::IPAddrRange-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::OSS-000.00",
        "target": "CMZJ::RMS-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::CustomerAddrMgr-000.01",
        "target": "CMZJ::SubNet16-000.01",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::WAN-000.00",
        "target": "CMZJ::CustomerAddrMgr-000.01",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::E2CVPN-000.00",
        "target": "CMZJ::SubNet16-000.01",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::CPE-000.01",
        "target": "CMZJ::WanAccess-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::EOMS-000.00",
        "target": "CMZJ::LeasedLine-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::OSS-000.00",
        "target": "CMZJ::EOMS-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::CPE-000.01",
        "target": "CMZJ::VPCAccess-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::CloudPlatform-000.00",
        "target": "CMZJ::SiteAccess-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::Cloud-000.00",
        "target": "CMZJ::CloudPlatform-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::E2CVPN-000.01",
        "target": "CMZJ::W2C-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::SubNet24VLAN-000.00",
        "target": "CMZJ::SubConnection-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::SubConnMgr-000.00",
        "target": "CMZJ::SubNet24VLAN-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::RMS-000.00",
        "target": "CMZJ::SubConnMgr-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::W2C-000.00",
        "target": "CMZJ::WanNode-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::WanCE-000.00",
        "target": "CMZJ::CloudAccess-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::WAN-000.00",
        "target": "CMZJ::WanCE-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::W2C-000.00",
        "target": "CMZJ::CloudNode-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::CloudCE-000.00",
        "target": "CMZJ::VPNAccess-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::Cloud-000.00",
        "target": "CMZJ::CloudCE-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::E2CVPN-000.01",
        "target": "CMZJ::RouteCfg-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::CloudAccess-000.00",
        "target": "CMZJ::VPCRoute-000.00",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }, {
        "source": "CMZJ::Customer-000.00",
        "target": "CMZJ::E2CVPN-000.01",
        "state": 0,
        "linkType": 1,
        "arrowType": 0
    }],
    "links2": [{
        "source": "CMZJ::CPE-000.01",
        "target": "CMZJ::SubNet30-000.00",
        "state": 1,
        "linkType": 0,
        "arrowType": 0
    }, {
        "source": "CMZJ::WanAccess-000.00",
        "target": "CMZJ::LeasedLine-000.00",
        "state": 1,
        "linkType": 0,
        "arrowType": 0
    }, {
        "source": "CMZJ::VPCAccess-000.00",
        "target": "CMZJ::SiteAccess-000.00",
        "state": 1,
        "linkType": 0,
        "arrowType": 0
    }, {
        "source": "CMZJ::W2C-000.00",
        "target": "CMZJ::SubConnection-000.00",
        "state": 1,
        "linkType": 0,
        "arrowType": 0
    }, {
        "source": "CMZJ::WanNode-000.00",
        "target": "CMZJ::CloudAccess-000.00",
        "state": 1,
        "linkType": 0,
        "arrowType": 0
    }, {
        "source": "CMZJ::CloudNode-000.00",
        "target": "CMZJ::VPNAccess-000.00",
        "state": 1,
        "linkType": 0,
        "arrowType": 0
    }, {
        "source": "CMZJ::RouteCfg-000.00",
        "target": "CMZJ::VPCRoute-000.00",
        "state": 1,
        "linkType": 0,
        "arrowType": 0
    }]
}